http {
	server {
		listen ;                         # Empty listen rule
		listen 127.0.0.1:;               # Only IP w/ ":"
		listen :8080;                    # Only port w/ ":"
		listen 257.0.0.1:10000;          # Wrong values

		server_name qkwdm.com;
		root /default;
		index /index.html;
		client_max_body_size 1k 5b;
		upload_dir /uploads;
		request_timeout 1d 4h 30m 20s 5ms;
		error_page 404 404.html;
		error_page 403 403.html;

		location / {
			allow_methods GET POST DELETE PUT;
			index default_index.html;
			autoindex off;
			alias /default/;

			cgi .php /usr/bin/php;
			cgi .sh /bin/bash;
			cgi .py /Users/lgreau/.brew/bin/python3;
			cgi .pl /usr/bin/perl;
			cgi .rb /usr/bin/ruby;
			cgi .png test_path_to_executable;
		}
	}
}
