echo "Content-type: text/html"
echo ""
echo "<!DOCTYPE html>"
echo "<html lang=\"en\">"
echo "<head>"
echo "    <meta charset=\"UTF-8\">"
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
echo "    <title>Shell CGI Example</title>"
echo "</head>"
echo "<body>"
echo "    <h1>Welcome to the Shell CGI Example</h1>"
echo "    <p>This is a simple example of a CGI script written in a shell script.</p>"
echo "    <p>Current Date and Time: $(date)</p>"
echo "</body>"
echo "</html>"
